#!/usr/bin/env tsx
/**
 * Regenerate the ADR index table in docs/decisions/README.md.
 *
 * The index is generated rather than hand-kept because staleness is the
 * specific failure mode that killed this repo's two previous decision-keeping
 * habits. A hand-maintained table is one forgotten edit away from lying, and an
 * index that lies is worse than no index — readers stop trusting it, then stop
 * using it.
 *
 * Nothing here is duplicated into frontmatter. Each record already carries its
 * number and title in the H1 and its status in the header line; the only fact
 * the index adds is the one-line summary, which lives in the ADR because a
 * reader opening it wants that sentence too.
 *
 * Usage:
 *   pnpm adr:index          rewrite the table
 *   pnpm adr:index --check  exit 1 if the table is out of date (CI)
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DECISIONS_DIR = join(REPO_ROOT, 'docs', 'decisions')
const README = join(DECISIONS_DIR, 'README.md')

const START = '<!-- adr-index:start -->'
const END = '<!-- adr-index:end -->'

type Adr = { num: string; title: string; status: string; summary: string; file: string }

/** `# 0002 — Corpus paths and library URLs are separate namespaces` */
const H1 = /^#\s+(\d{4})\s+[—-]\s+(.+?)\s*$/m
/** `**Date:** 2026-08-22 · **Status:** Accepted · **Supersedes** 0004` */
const STATUS = /\*\*Status:\*\*\s*([^·\n]+?)(?:\s*·|\s*$)/m
/** The italic one-liner directly beneath the header line. */
const SUMMARY = /^\s*_(.+?)_\s*$/m

function parse(file: string): Adr | null {
  const raw = readFileSync(join(DECISIONS_DIR, file), 'utf-8')
  const h1 = H1.exec(raw)
  if (!h1) {
    console.warn(`  ⚠ ${file}: no "# NNNN — Title" heading; skipped`)
    return null
  }
  const status = STATUS.exec(raw)?.[1]?.trim() ?? 'Unknown'
  const summary = SUMMARY.exec(raw)?.[1]?.trim() ?? ''
  if (!summary) console.warn(`  ⚠ ${file}: no italic one-line summary under the header`)
  return { num: h1[1], title: h1[2], status, summary, file }
}

function render(adrs: Adr[]): string {
  const rows = adrs.map((a) => {
    // A superseded decision must read as superseded at a glance, or someone
    // acts on a reversed record.
    const status = /^Superseded/i.test(a.status) ? `~~${a.status}~~` : a.status
    return `| [${a.num}](${a.file}) | **${a.title}** | ${status} | ${a.summary} |`
  })
  return [
    START,
    '',
    '| # | Decision | Status | |',
    '|---|---|---|---|',
    ...rows,
    '',
    `_${adrs.length} record${adrs.length === 1 ? '' : 's'}. Generated by \`pnpm adr:index\` — edit the ADRs, not this table._`,
    END,
  ].join('\n')
}

function main() {
  const check = process.argv.slice(2).includes('--check')

  const files = readdirSync(DECISIONS_DIR)
    .filter((f) => /^\d{4}-.*\.md$/.test(f))
    .sort()

  const adrs = files.map(parse).filter((a): a is Adr => a !== null)

  const readme = readFileSync(README, 'utf-8')
  const s = readme.indexOf(START)
  const e = readme.indexOf(END)
  if (s === -1 || e === -1) {
    console.error(`${README} is missing the ${START} / ${END} markers.`)
    process.exit(1)
  }

  const next = readme.slice(0, s) + render(adrs) + readme.slice(e + END.length)

  if (next === readme) {
    console.log(`Index is current — ${adrs.length} record(s).`)
    return
  }

  if (check) {
    console.error(`ADR index is out of date. Run: pnpm adr:index`)
    process.exit(1)
  }

  writeFileSync(README, next, 'utf-8')
  console.log(`Rewrote the index — ${adrs.length} record(s).`)
}

main()
