#!/usr/bin/env tsx
/**
 * knowledge/iching/principles/*.md  →  INDEX.md + principles.yaml
 *
 *   pnpm xenso:principles
 *
 * The index is generated because a hand-kept index of anything goes stale — that
 * is the inherited `edited-or-generated` principle, applied to the directory
 * that holds it.
 *
 * It also **verifies every `evidence:` anchor resolves to a real heading in the
 * file it names.** A principle whose evidence has rotted is a rule with nothing
 * behind it, and the rot is invisible until someone follows the link. Here it is
 * a build error instead.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { load } from 'js-yaml'

const ROOT = resolve(__dirname, '..', '..')
const DIR = join(ROOT, 'knowledge', 'iching', 'principles')

type Entry = {
  id: string
  title: string
  status: 'provisional' | 'active' | 'superseded'
  since: string
  trigger: string
  applies: string[]
  evidence: string[]
  check: string
  supersedes: string[]
  file: string
}

let failures = 0
const fail = (m: string) => {
  console.log(`  ✗ ${m}`)
  failures++
}

/** GitHub's heading-anchor rule, near enough: lowercase, drop punctuation, spaces to hyphens. */
function slug(heading: string): string {
  return heading
    .trim()
    .toLowerCase()
    .replace(/[`*_~]/g, '')
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/\s/g, '-')
}

function headingsOf(path: string): Set<string> {
  const out = new Set<string>()
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = /^#{1,6}\s+(.*?)\s*$/.exec(line)
    if (m) out.add(slug(m[1]))
  }
  return out
}

const entries: Entry[] = readdirSync(DIR)
  .filter(f => f.endsWith('.md') && f !== 'README.md' && f !== 'INDEX.md')
  .sort()
  .map(f => {
    const text = readFileSync(join(DIR, f), 'utf8')
    const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text)
    if (!m) throw new Error(`${f}: no frontmatter`)
    const fm = load(m[1]) as Omit<Entry, 'file'>
    if (fm.id !== f.replace(/\.md$/, '')) fail(`${f}: id "${fm.id}" does not match the filename`)
    for (const field of ['title', 'status', 'since', 'trigger', 'applies', 'check'] as const) {
      if (fm[field] === undefined) fail(`${f}: missing ${field}`)
    }
    if (fm.status === 'active' && (fm.evidence ?? []).length < 2) {
      fail(`${f}: status is active but carries ${(fm.evidence ?? []).length} case(s) — two independent cases is the threshold`)
    }
    return { ...fm, file: f }
  })

// Evidence must point somewhere real.
const cache = new Map<string, Set<string> | null>()
let anchors = 0
for (const e of entries) {
  for (const ref of e.evidence ?? []) {
    const [rel, anchor] = ref.split('#')
    const path = join(DIR, rel)
    if (!cache.has(path)) cache.set(path, existsSync(path) ? headingsOf(path) : null)
    const heads = cache.get(path)
    if (heads === null) { fail(`${e.file}: evidence names a file that does not exist — ${rel}`); continue }
    if (anchor && !heads!.has(anchor)) { fail(`${e.file}: evidence anchor not found — ${ref}`); continue }
    anchors++
  }
}

const MARK: Record<string, string> = { active: '✅', provisional: '🔶', superseded: '⛔' }
const byStatus = (s: string) => entries.filter(e => e.status === s).length

const index = [
  '# Principles — index',
  '',
  '*Generated by `pnpm xenso:principles` from the frontmatter of each entry.*',
  '**Never edit this file by hand.** Edit the entry, then rebuild.',
  '',
  `**${byStatus('active') + byStatus('provisional')} in force** — ${byStatus('active')} active, ${byStatus('provisional')} provisional.`,
  '',
  'These are the rules **this** project learned. The Tao Te Ching project\'s twenty-seven apply here in full and are not repeated —',
  'see [`../method.md`](../method.md) § 6 for the ones that fire hardest on this book.',
  '',
  '*A principle fires on its **trigger**. Read that column first.*',
  '',
  '| | When it fires | The rule | Applies to | Enforced by |',
  '|---|---|---|---|---|',
  ...entries
    .slice()
    .sort((a, b) => (a.status === b.status ? a.title.localeCompare(b.title) : a.status === 'active' ? -1 : 1))
    .map(e => `| ${MARK[e.status] ?? '?'} | ${e.trigger} | **[${e.title}](${e.file})** | ${(e.applies ?? []).join(' · ')} | ${e.check === 'none' ? '—' : `\`${e.check}\``} |`),
  '',
].join('\n')

writeFileSync(join(DIR, 'INDEX.md'), index)

const yaml = [
  '# Generated by pnpm xenso:principles. Do not edit by hand.',
  'principles:',
  ...entries.flatMap(e => [
    `  - id: ${e.id}`,
    `    title: ${JSON.stringify(e.title)}`,
    `    status: ${e.status}`,
    `    since: ${e.since}`,
    `    trigger: ${JSON.stringify(e.trigger)}`,
    `    applies: [${(e.applies ?? []).join(', ')}]`,
    `    check: ${e.check}`,
    `    evidence:`,
    ...(e.evidence ?? []).map(x => `      - ${JSON.stringify(x)}`),
  ]),
  '',
].join('\n')
writeFileSync(join(DIR, 'principles.yaml'), yaml)

console.log(`\nprinciples`)
console.log(`  ${entries.length} entries — ${byStatus('active')} active, ${byStatus('provisional')} provisional, ${byStatus('superseded')} superseded`)
console.log(`  ${anchors} evidence anchors, all resolving`)
console.log(`  → knowledge/iching/principles/INDEX.md, principles.yaml`)
console.log(failures === 0 ? '\n✓ principles verified\n' : `\n✗ ${failures} failure(s)\n`)
process.exit(failures ? 1 : 0)
